apiVersion: 1
deleteDatasources:
  - name: influxdb
    orgId: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    uid: influxdb
    url: http://influxdb:8086
    database: ntopng
    user: ntopng
    secureJsonData:
      password: ${INFLUXDB_USER_PASSWORD}
    jsonData:
      httpMode: GET
    editable: true
